/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_xy_jni_NdkJniUtil */

#ifndef _Included_com_example_xy_jni_NdkJniUtil
#define _Included_com_example_xy_jni_NdkJniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_xy_jni_NdkJniUtil
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_xy_jni_NdkJniUtil_getCLanguageString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
